export const categories = [
    "animals",
    "anime",
    "anti-malware",
    "art & design",
    "books",
    "business",
    "calendar",
    "cloud storage & file sharing",
    "continuous integration",
    "cryptocurrency",
    "currency exchange",
    "data validation",
    "development",
    "dictionaries",
    "documents & productivity",
    "environment",
    "events",
    "finance",
    "food & drink",
    "games & comics",
    "geocoding",
    "government",
    "health",
    "jobs",
    "machine learning",
    "music",
    "news",
    "open data",
    "open source projects",
    "patent",
    "personality",
    "photography",
    "science & math",
    "security",
    "shopping",
    "social",
    "sports & fitness",
    "test data",
    "text analysis",
    "tracking",
    "transportation",
    "url shorteners",
    "vehicle",
    "video",
    "weather"
];
